uboot-mediatek: mt7622/mt7981/mt7986/mt7988: fix support PSTORE/ramoops
u-boot missing driver 'psci-sysreset' needs to be enabled but cannot be build

needs build time configuraton:
CONFIG_SYSRESET=y
CONFIG_SYSRESET_PSCI=y

https://github.com/openwrt/openwrt/commit/cc201759b69e6e61736005864d99cdac44b7e19f
https://github.com/openwrt/openwrt/commit/3eb354f999a3687f9ae547899b0f5ec2b10185ab
https://github.com/openwrt/openwrt/commit/85581cc89a0a4db8df0675458ef54534fdd65e1f

1. u-boot fails to find and bind driver 'psci-sysreset'

[..]
drivers/core/lists.c:163- Cannot find driver 'psci-sysreset'
drivers/clk/clk-uclass.c:116- prop: returning err=-2
[..]

2. "CONFIG_SYSRESET_PSCI" fails to compile

[..]
aarch64-openwrt-linux-musl-ld: drivers/sysreset/sysreset-uclass.o: in function `reset_cpu':
/home/sven/src/openwrt/build_dir/target-aarch64_cortex-a53_musl/u-boot-mt7981_zyxel-nwa50ax-pro/u-boot-2025.10/drivers/sysreset/sysreset-uclass.c:116: multiple definition of `reset_cpu'; arch/arm/mach-mediatek/mt7981/init.o:/home/sven/src/openwrt/build_dir/target-aarch64_cortex-a53_musl/u-boot-mt7981_zyxel-nwa50ax-pro/u-boot-2025.10/arch/arm/mach-mediatek/mt7981/init.c:30: first defined here
make[3]: *** [Makefile:2029: u-boot] Error 1
[..]